// Handles mail icon window logic
const mailIcon = Array.from(document.querySelectorAll('.icon-item'))
    .find(item => item.querySelector('.icon-label')?.textContent.trim().toLowerCase() === 'mail');
if (mailIcon) {
    const mailLink = mailIcon.querySelector('a');
    if (mailLink) {
        mailLink.addEventListener('click', function(e) {
            e.preventDefault();
            const win = document.createElement('div');
            win.className = 'tab';
            win.style.position = 'absolute';
            win.style.left = '35vw';
            win.style.top = '18vh';
            win.style.width = '28vw';
            win.style.height = '40vh';
            win.style.zIndex = '20';
            win.style.background = '#220135';
            win.style.border = 'groove 3px orange';
            win.style.borderRadius = '10px';
            win.style.color = 'white';
            win.style.display = 'flex';
            win.style.flexDirection = 'column';
            const nav = document.createElement('div');
            nav.className = 'nav';
            const closeBtn = document.createElement('button');
            closeBtn.textContent = 'x';
            closeBtn.onclick = () => win.remove();
            const maxBtn = document.createElement('button');
            maxBtn.textContent = '+';
            nav.appendChild(closeBtn);
            nav.appendChild(maxBtn);
            const tabcontent = document.createElement('div');
            tabcontent.className = 'tabcontent';
            tabcontent.style.height = 'calc(100% - 40px)';
            tabcontent.style.overflow = 'auto';
            tabcontent.style.display = 'flex';
            tabcontent.style.flexDirection = 'column';
            tabcontent.style.alignItems = 'center';
            tabcontent.style.justifyContent = 'center';
            const form = document.createElement('form');
            form.style.width = '90%';
            form.style.margin = 'auto';
            form.style.display = 'flex';
            form.style.flexDirection = 'column';
            form.style.gap = '10px';
            const toLabel = document.createElement('label');
            toLabel.textContent = 'To:';
            toLabel.style.textAlign = 'left';
            toLabel.style.fontFamily = '"Share Tech", sans-serif';
            const toInput = document.createElement('input');
            toInput.type = 'email';
            toInput.value = 'james1deal@pm.me';
            toInput.readOnly = true;
            toInput.style.background = '#3a015c';
            toInput.style.color = 'yellow';
            toInput.style.border = '1px solid orange';
            toInput.style.borderRadius = '3px';
            toInput.style.padding = '4px';
            const subjectLabel = document.createElement('label');
            subjectLabel.textContent = 'Subject:';
            subjectLabel.style.textAlign = 'left';
            subjectLabel.style.fontFamily = '"Share Tech", sans-serif';
            const subjectInput = document.createElement('input');
            subjectInput.type = 'text';
            subjectInput.placeholder = 'Subject';
            subjectInput.style.background = '#3a015c';
            subjectInput.style.color = 'yellow';
            subjectInput.style.border = '1px solid orange';
            subjectInput.style.borderRadius = '3px';
            subjectInput.style.padding = '4px';
            const bodyLabel = document.createElement('label');
            bodyLabel.textContent = 'Message:';
            bodyLabel.style.textAlign = 'left';
            bodyLabel.style.fontFamily = '"Share Tech", sans-serif';
            const bodyInput = document.createElement('textarea');
            bodyInput.value = "I love your website, James! You're hired!";
            bodyInput.readOnly = true;
            bodyInput.style.background = '#3a015c';
            bodyInput.style.color = 'yellow';
            bodyInput.style.border = '1px solid orange';
            bodyInput.style.borderRadius = '3px';
            bodyInput.style.padding = '4px';
            bodyInput.style.height = '100px';
            const sendBtn = document.createElement('button');
            sendBtn.type = 'submit';
            sendBtn.textContent = 'Send';
            sendBtn.style.background = 'orange';
            sendBtn.style.color = '#32004f';
            sendBtn.style.border = 'none';
            sendBtn.style.borderRadius = '3px';
            sendBtn.style.fontWeight = 'bold';
            sendBtn.style.cursor = 'pointer';
            sendBtn.style.marginTop = '10px';
            form.appendChild(toLabel);
            form.appendChild(toInput);
            form.appendChild(subjectLabel);
            form.appendChild(subjectInput);
            form.appendChild(bodyLabel);
            form.appendChild(bodyInput);
            form.appendChild(sendBtn);
            tabcontent.appendChild(form);
            win.appendChild(nav);
            win.appendChild(tabcontent);
            document.body.appendChild(win);
        });
    }
}
